# Generated by Django 4.2.7 on 2023-11-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified_email_emailverifycation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifycation',
            new_name='EmailVerification',
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Подтверждение почты', 'verbose_name_plural': 'Подтверждение почты'},
        ),
        migrations.RenameField(
            model_name='emailverification',
            old_name='expereation',
            new_name='expiration',
        ),
    ]
